---
- hosts: all
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Install Redis server
      apt:
        name: redis-server
        state: present

    - name: Ensure userapi dependencies are installed
      npm:
        path: /home/vagrant/userapi
        production: no
