---
- hosts: all
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install Redis
      apt:
        name: redis-server
        state: present

    - name: Install dependencies
      shell: npm install
      args:
        chdir: /vagrant/userapi

    - name: Run app (development mode)
      shell: node src/index.js
      args:
        chdir: /vagrant/userapi
      async: 10
      poll: 0
