Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "userapi"

  config.vm.network "forwarded_port", guest: 3005, host: 3005

  config.vm.synced_folder "../userapi", "/home/vagrant/userapi"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/provision.yml"
  end
end

